spring:
  flyway:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/meceariadeposito2
    username: postgres
    password: Admin


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


